name: vantra_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
       

# Native Splash Configuration
flutter_native_splash:         
  image: assets/images/vantra_logo.png
  android: true
  ios: true
  color: "#6C8E58"  

# App Icon Configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/vantra_icon.png"
